kaitai/kaitaistream.cpp

on MSVC &result[len] is illegal and cause crash (assert)

fix: read_bytes

---

kaitai/kaitaistream.cpp

The line
uint64_t mask = (1 << n) -1;
might lead to unexpected results. "1" might be of type (signed) integer. An integer might have 32 bits or less. (1 << n) will have the same datatype as "1". This causes unintended behavior for n >= 32.
let type that is left-shiftet to generate a bitmask be of type uint64_t so that bitfields with length 32 to 63 are read properly; add special case for 64 bitfield case; more than 64 bits are not supported at the moment

correct reading bitfields with sizes between 32bit and 64bit

---

kaitai/kaitaistream.cpp

byteswap.h is an unportable GNU extension and it is missing on macOS. This commit provides a compatibility layer which relies on the `OSSwapInt*` macros defined in `<libkern/OSByteOrder.h>`.  
This commit defines the required information inline in `kaitaistream.cpp`: if preferable, it might be implemented in a separate header (e.g. `portable_byteswap.h`).
(Relevant issue: https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/issues/10)

Add build support for macOS, which is missing byteswap.h

---

CMakeLists.txt
kaitai/kaitaistream.cpp
kaitai/kaitaistream.h

I added support for Visual C++.
Also moved zlib & iconv support to CMakeList and make them optional.
For Visual C++ 2015 update 3 and 2017 we can install zlib & iconv using [vcpkg](https://github.com/Microsoft/vcpkg)
```
vcpkg install zlib libiconv
cmake -DCMAKE_TOOLCHAIN_FILE=<vcpkg_root>/scripts/buildsystems/vcpkg.cmake .
```
Issues: kaitai-io/kaitai_struct#124 #11

VC++ support

---

kaitai/kaitaistream.cpp
kaitai/kaitaistream.h
kaitai/kaitaistruct.h

Summary:
1. Fix warnings
2. Pass string as reference
3. Fix crashing when we try to read this structure if readed string size == 0
```yaml
string:
seq:
- id: size
type: u2
- id: desc
type: str
size: size
```

Code improvment

---

CMakeLists.txt

In this way someone can decide during compile time if use string encoding or not.
To disable string encoding via iconv simply compile with
`build$ cmake -DUSE_STRING_ENCODING=OFF ..`

Added CMake option

---

CMakeLists.txt

Hi, 
On the Mac I was not able to link the symbols `iconv`, `iconv_open` and `iconv_close` called in `runtime/cpp_stl/kaitaistream.cpp`.  This was due to the `find_library ICONV_LIBRARIES` line in `CMakeLists.txt` looking for `libiconv`, when on the Mac it needs to look for `iconv`.  The same line looks for `c` so it was finding `/usr/lib/libc` and not `/usr/lib/libiconv`, which is installed.  `libc` of course can not resolve the `iconv` symbols.  I took out `c` and added `iconv`.  
I also added two lines to install the headers in a `kaitai` subdirectory (as the generated C++ files look for `kaitai/kaitaistruct.h`).  One line to add `PUBLIC_HEADER` to `set_target_properties`, and one line in the `install` target to install the two `.h` files.
Tested on Mac and Linux but not Windows.

Edit for Mac: runtime/cpp_stl/CMakeLists.txt

---

kaitai/kaitaistream.cpp
kaitai/kaitaistream.h

Fix sign conversion, sign comparison, strict aliasing and type punning warnings when compiling using GCC.
This should not affect the behavior in any way, kaitai tests results did not change.
Any feedback is welcomed and appreciated.
This pull depends on https://github.com/kaitai-io/kaitai_struct_compiler/pull/187, both of them should be merged or none will work.

Fix GCC type warnings

---

kaitai/kaitaistream.cpp
kaitai/kaitaistream.h

https://en.cppreference.com/w/cpp/io/basic_istringstream/basic_istringstream (3) takes `const std::string&` so it looks appropriate to take the same in `kaitai::kstream` constructor working with `std::string`.
Resolves https://github.com/kaitai-io/kaitai_struct/issues/806

Fix kstream constructor which uses std::string for initialization

---

.build/build
.build/build.ps1
.build/run-unittest
.build/run-unittest.ps1
.github/workflows/build.yml
kaitai/kaitaistream.h

* Adds GitHub Actions-based CI workflows to build library + unit tests and do a basic test run.
* Implements 2x2 scripts in `.build/` for Linux/Windows and build/run steps.
* Adds CI workflows for Linux and Windows.
* Fixes one warning in .h file (problem proven by [CI failing run](https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/actions/runs/5154249448/jobs/9282479655), successful unit tests prove that nothing has been broken after the fix).
Known caveats:
* Tests rely on availability of GTest, but different OSes have different ways to install and versions to offer:
* For Linux, it's installed in CI using apt (takes ~15-20s). As of now, this gets *GTest 1.11.0-3*.
* For Windows, it's more complicated: there's no binary build, so we utilize vcpkg to download and build gtest …

GitHub Actions CI for running unit tests

---

.github/workflows/build.yml
Makefile.gcc4
kaitai/kaitaistream.cpp
tests/gtest-nano.h
tests/unittest.cpp

This add CI support for ancient Ubuntu 7.10 and ancient gcc 4.1.2. This PR is based off https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/pull/56, and it supposed to be reviewed after that.
Ubuntu 7.10 ships with:
```
gcc (GCC) 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)
Copyright (C) 2006 Free Software Foundation, Inc.
cmake version 2.4-patch 7
```
This one is challenging:
* It's impossible to run git clone inside this container (as old git would use older protocols not supported anymore by GitHub, and also standard `actions/checkout@v3` will depend on NodeJS/npm, which are not available in this container). To work around this, we start/stop container manually and use targeted execution of specific build/run commands only inside the container, keeping git and networking …

Add CI support for gcc 4.1.2 / Ubuntu 7.10

---

CMakeLists.txt
Common.cmake
tests/CMakeLists.txt
tests/unittest.cpp

This adds basic tests for `bytes_to_str`. Supposed to be setting the baseline and being equivalent for different implementations that I'd like to add.
Pretty straightforward, a few notes:
* Does not risk non-ASCII, so deliberately stays in `\xFF` mode for all strings (both non-UTF8 and UTF8).
* We need to propagate KS_STR_ENCODING_xx to test units as well, for that it includes a small refactoring to extract the common setting part in both CMakeLists.

Basic bytes_to_str tests

---

CMakeLists.txt

This PR replaces manual searching for Iconv with a find_package because there is [a find module for Iconv in CMake](https://cmake.org/cmake/help/latest/module/FindIconv.html) which is available since version 3.11. It is not merely a step towards modernization, it allows to cross-build this library when using Android NDK. This PR also sets 3.11 as minimum required version of CMake which is a rather reasonable because versions of CMake > 3.11 [are widely available in Linux distros](https://pkgs.org/download/cmake) (it goes without saying that you can also just download latest CMake version and install on any Linux distro). Zlib now is also linked as a target instead of using variables but this target [is available since CMake 3.1](https://cmake.org/cmake/help/latest/module/FindZLIB.html).

Use targets in CMake instead of variables

---

kaitai/exceptions.h
kaitai/kaitaistream.cpp
tests/unittest.cpp

This sets up a three new C++ exceptions related to surfacing encoding issues in a better, more structured way than a generic `std::runtime_error` we've been throwing so far:
* bytes_to_str_error: generic encoding problem
* unknown_encoding: problem related to unknown encoding being chosen an runtime
* illegal_seq_in_encoding: problem related to encoding engine being unable to perform encoding due to invalid sequence encountered in the input bytes
Added implementations and more detailed exceptions throwing/checking for both ICONV and WIN32API implementations.

Encoding-related exceptions

---

CMakeLists.txt

- I am trying to update kaitai_struct_cpp_stl_runtime port in Vcpkg repository to the latest version, which supports creating a static library. 
- [PR in Vcpkg repository](https://github.com/microsoft/vcpkg/pull/34256).
- It seems like right now, for using the CMakeLists.txt file, it is mandatory to install GTest as well. Check [CMakeLists.txt](https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/blob/master/tests/CMakeLists.txt) which is included always.
- Given that at Vcpkg and even users may not be interested in building the tests (which forces having GTest), I suggest adding a CMake option for allowing to skip the build of tests.

Add BUILD_TESTS CMake option

---

kaitai/exceptions.h

In 0.10.1, I met compilation errors on gcc 13:
```
In file included from kaitai/kaitaistream.cpp:2:
kaitai/exceptions.h:118:35: error: expected unqualified-id before ‘const’
118 |     validation_not_equal_error<T>(const T& expected, const T& actual, kstream* io, const std::string src_path):
|                                   ^~~~~
kaitai/exceptions.h:118:35: error: expected ‘)’ before ‘const’
118 |     validation_not_equal_error<T>(const T& expected, const T& actual, kstream* io, const std::string src_path):
|                                  ~^~~~~
|                                   )
kaitai/exceptions.h:127:13: error: template-id not allowed for destructor
127 |     virtual ~validation_not_equal_error<T>() KS_NOEXCEPT {};
|             ^
...
```
They are caused by `<T>` in …

remove template id from constructor/destructor

---

Common.cmake

See https://stackoverflow.com/a/57637463/12940655:
> Command `add_compile_options` affects only on the targets, which are **created after** the command is invoked. Current command documentation says:
>
> > Adds options to the `COMPILE_OPTIONS` directory property.
> Because you call `add_library` before the `add_compile_options`, this library's options are not changed.
In our case, this meant that only the "unittest" project actually received these compilation options (ironically not due to the `include(../Common.cmake)` directive in /tests/CMakeLists.txt, but because of `include(Common.cmake)` preceding `add_subdirectory(tests)` in root /CMakeLists.txt), not the main `kaitai_struct_cpp_stl_runtime` project.
So this pull request replaces `add_compile_options` with `target_compile_options`, …

Fix unapplied CMake property `add_compile_options`

---

kaitai/kaitaistream.cpp
tests/unittest.cpp

Kudos to @roelschroeven for noticing this case (https://github.com/roelschroeven/kaitai_struct_cpp_stl_runtime/commit/29d57ae618b14cc6e90a73d49478869517e5d990) - the patch in the Win32 API variant of `bytes_to_str()` is the same.

Add bytes_to_str() tests for empty string, fix Win32 API variant

---

Common.cmake
kaitai/kaitaistream.cpp
kaitai/kaitaistream.h

Solves https://github.com/kismetwireless/kismet/issues/518

read_f{4,8}{be,le}(): fix violations of strict aliasing rules

---

.github/workflows/build.yml
kaitai/kaitaistream.cpp
tests/unittest.cpp

Adds proven support for FreeBSD and NetBSD. Uses GH Actions for 2 new workflows (which internally download an image for a VM and runs it in qemu emulator on Ubuntu host).

Support FreeBSD 14.0 + NetBSD 10.0 + add testing

---

.build/install-gtest
.github/workflows/build.yml
kaitai/exceptions.h
kaitai/kaitaistream.cpp
kaitai/kaitaistream.h
tests/gtest-nano.h
tests/unittest.cpp

Until now, some parts of the code used symbols from the standard library without including the corresponding standard library header using `#include` to ensure that the symbol is defined. That is, they silently assumed that the header has been already included by "someone else".
These assumptions were sometimes met in our code due to transitive inclusions. For example, the missing `#include <stdexcept>` in `tests/unittest.cpp` would not turn into a compile error, because `tests/unittest.cpp` included `kaitai/exceptions.h`, which contains `#include <stdexcept>`. However, it is discouraged to rely on transitive inclusions, see https://google.github.io/styleguide/cppguide.html#Include_What_You_Use:
> Do not rely on transitive inclusions. This allows people to remove no-longer-needed …

Make each .cpp/.h file self-sufficient in `#include`s

---

CMakeLists.txt

When using the runtime with zlib support with cmake, the required KS_ZLIB flags is not propagated to the linking target.

Make KS_ZLIB flag public

---

.build/gtest-v1.8.1-fix-Werror-maybe-uninitialized.patch
.build/install-gtest
.github/workflows/build.yml
kaitai/kaitaistream.cpp
kaitai/kaitaistream.h
tests/CMakeLists.txt
tests/unittest.cpp

As mentioned in the code comment in `kaitai/kaitaistream.cpp`, this approach follows what `std::to_string` is doing:
https://en.cppreference.com/w/cpp/string/basic_string/to_string
Avoiding templates and separating signed and unsigned cases has been already suggested by @webbnh in https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/pull/50.
The motivation for this change is that this new version of `to_string` also accepts values of unscoped enums that can be implicitly converted to integers, just like `std::to_string` does. For example, you can do `kaitai::kstream::to_string(FRUIT_APPLE)` just like you can do `std::to_string(FRUIT_APPLE)`, where `FRUIT_APPLE` is an unscoped enum member:
```cpp
enum fruit_t {
FRUIT_APPLE = 2,
FRUIT_ORANGE = 5
};
```
This simplifies the translation …

to_string(): replace template with 6 overloads, simplify

---

.github/workflows/build.yml

Something has changed in how GH Action runs FreeBSD builds. Looks like `gcc --version` with no gcc available now breaks the build of error.
This mitigates the problem.

Fix FreeBSD build
